[tool.poetry]
name = "tcas-engineer"
version = "0.1.0"
description = ""
authors = ["BrossBoy <phongphiphatkhunchit@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
